# Generated by Django 3.0.2 on 2020-02-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0002_auto_20200121_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='First_Name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Mobile_No',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Username',
        ),
        migrations.AddField(
            model_name='user',
            name='slide_img',
            field=models.ImageField(default='', upload_to='usersite/slider'),
        ),
    ]
