# Generated by Django 3.0.2 on 2020-02-15 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0004_auto_20200215_1416'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slider',
            new_name='slideimg',
        ),
    ]
