# Generated by Django 3.0.2 on 2020-02-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0005_auto_20200215_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideimg',
            name='slide_img',
            field=models.CharField(default='', max_length=30),
        ),
    ]
