# Generated by Django 3.0.2 on 2020-02-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0007_auto_20200217_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='demoimg',
            field=models.ImageField(default='', upload_to='usersite/slider'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Address',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Business_Name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Customer_Name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Email',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Mobile_No',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Password',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Username',
            field=models.CharField(default='', max_length=30),
        ),
    ]
