# Generated by Django 3.0.2 on 2020-02-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0008_auto_20200217_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='org',
            old_name='Address',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='org',
            old_name='Company_Name',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='org',
            old_name='Owner_Name',
            new_name='Last_name',
        ),
        migrations.AddField(
            model_name='org',
            name='Age',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='org',
            name='Mobile_No',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='Age',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='Mobile_No',
            field=models.IntegerField(default=''),
        ),
    ]
