# Generated by Django 3.0.2 on 2020-02-17 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0009_auto_20200217_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='org',
            old_name='First_Name',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='org',
            old_name='Gender',
            new_name='Company_Name',
        ),
        migrations.RenameField(
            model_name='org',
            old_name='Last_name',
            new_name='Owner_Name',
        ),
        migrations.RemoveField(
            model_name='org',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='org',
            name='Mobile_No',
        ),
    ]
