# Generated by Django 3.0.2 on 2020-02-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0010_auto_20200217_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='Mobile_No',
            field=models.IntegerField(default=0),
        ),
    ]
