# Generated by Django 3.0.2 on 2020-02-17 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0011_auto_20200217_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Mobile_No',
        ),
    ]
