# Generated by Django 3.0.2 on 2020-02-17 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0012_auto_20200217_1252'),
    ]

    operations = [
        migrations.DeleteModel(
            name='org',
        ),
    ]
