# Generated by Django 3.0.2 on 2020-02-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0013_delete_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='Mobile_No',
            field=models.IntegerField(default=0),
        ),
    ]
