# Generated by Django 3.0.2 on 2020-02-17 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0015_auto_20200217_1623'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Org',
        ),
    ]
