# Generated by Django 3.0.2 on 2020-02-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0017_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Age',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='Mobile_No',
            field=models.CharField(default='', max_length=10),
        ),
    ]
