# Generated by Django 3.0.2 on 2020-02-17 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0018_auto_20200217_1648'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
