# Generated by Django 3.0.2 on 2020-02-17 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0021_remove_user_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Mobile_No',
        ),
    ]
