# Generated by Django 3.0.2 on 2020-02-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0022_remove_user_mobile_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Age',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='Mobile_No',
            field=models.CharField(default='', max_length=10),
        ),
    ]
