# Generated by Django 3.0.2 on 2020-02-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0024_auto_20200218_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Section', models.CharField(default='', max_length=30)),
                ('Header', models.CharField(default='', max_length=100)),
                ('Img', models.ImageField(default='', upload_to='usersite/UserUploadimg')),
                ('info_disc', models.CharField(default='', max_length=1000)),
                ('Approve', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cid', models.IntegerField(default=0)),
                ('Aid', models.IntegerField(default=0)),
                ('Date', models.DateField()),
                ('Amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Upload_Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_disc', models.CharField(default='', max_length=500)),
                ('Email', models.EmailField(max_length=50)),
                ('Mobile', models.IntegerField(default=10)),
            ],
        ),
    ]
