# Generated by Django 3.0.2 on 2020-02-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0025_info_user_payment_upload_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider_Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Img', models.ImageField(default='', upload_to='usersite/UserUploadimg')),
            ],
        ),
        migrations.AlterField(
            model_name='info_user',
            name='Approve',
            field=models.BooleanField(default=False),
        ),
    ]
