# Generated by Django 3.0.2 on 2020-02-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0026_auto_20200218_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider_img',
            name='Img',
            field=models.ImageField(default='', upload_to='usersite/slider'),
        ),
    ]
