# Generated by Django 3.0.2 on 2020-02-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0027_auto_20200218_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider_img',
            name='Img_Name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
