# Generated by Django 3.0.2 on 2020-02-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0029_auto_20200219_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='Img2',
        ),
        migrations.AddField(
            model_name='news',
            name='Date',
            field=models.DateField(default=''),
        ),
    ]
