# Generated by Django 3.0.2 on 2020-02-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0030_auto_20200219_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Date',
            field=models.DateField(),
        ),
    ]
