# Generated by Django 3.0.2 on 2020-02-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0031_auto_20200219_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Date',
            field=models.DateField(blank=True),
        ),
    ]
