# Generated by Django 3.0.2 on 2020-02-19 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0033_auto_20200219_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='Date',
        ),
    ]
