# Generated by Django 3.0.2 on 2020-02-19 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0035_news_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='Date',
        ),
    ]
