# Generated by Django 3.0.2 on 2020-02-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0036_remove_news_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='ndate',
            field=models.DateTimeField(default=0),
        ),
    ]
