# Generated by Django 3.0.2 on 2020-02-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0037_news_ndate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='ndate',
            field=models.DateTimeField(default=''),
        ),
    ]
