# Generated by Django 3.0.2 on 2020-02-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0041_news_ndate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='Desc',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='Disc',
            field=models.CharField(default='', max_length=500),
        ),
    ]
