# Generated by Django 3.0.2 on 2020-02-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0043_auto_20200219_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_portal',
            name='Job_Disc',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
