# Generated by Django 3.0.2 on 2020-02-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0045_job_portal_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='Dist',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='place',
            name='Place_Disc',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
