# Generated by Django 3.0.2 on 2020-03-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0046_auto_20200220_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='getuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=20)),
                ('Mobile', models.IntegerField(default=10)),
            ],
        ),
    ]
